### ISSUE TITLE
Module not in ecosystem

### ISSUE THREAD

**Issue by lukasvalle** [oposs/jsonhound#11]
It's not possible to install the modul using zef:
`No candidates found matching identity: JSONHound`

Direct install works fine:
`zef -v install git://github.com/oposs/jsonhound.git`

It seems that to be able to install it using zef, it has only to be added to 
`https://github.com/perl6/ecosystem/blob/master/META.list`

If ok for you, I can make a PR to the ecosystem to add 
`https://raw.githubusercontent.com/oposs/jsonhound/master/META6.json`

**Comment by oetiker** [comment]
by all means, please do so!

**Comment by lukasvalle** [comment]
done: https://github.com/perl6/ecosystem/pull/464
